// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    AppRestaurantInfo: typeof import('./components/AppRestaurantInfo.vue')['default']
    AppSelect: typeof import('./components/AppSelect.vue')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserHello: typeof import('./components/User/Hello.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
